# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 30 Dec 2013 03:25:47 +0000
*               @ALL          1
*               @user         8
